# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=90)),
                ('team', models.CharField(max_length=4)),
                ('angle', models.PositiveSmallIntegerField()),
                ('text_color', models.CharField(max_length=8)),
                ('color1', models.CharField(max_length=8)),
                ('color2', models.CharField(blank=True, max_length=8)),
                ('color3', models.CharField(blank=True, max_length=8)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
